dependencies:
  '@babel/cli': ^7.1.5
  '@babel/core': ^7.1.5
  '@babel/plugin-transform-runtime': ^7.1.0
  '@babel/preset-env': ^7.1.5
  '@babel/preset-react': ^7.0.0
  '@babel/runtime': ^7.1.5
  html-loader: ^0.4.5
  css-loader: ^0.28.4
  webpack: ^3.0.0
  webpack-dev-server: ^2.5.0
  babel-loader: ^8.0.0-beta.3
  handlebars-webpack-plugin: ^1.2.0
  copy-webpack-plugin: ^4.0.1
  sass-loader: ^6.0.6
  style-loader: ^0.18.2
  node-sass: ^4.5.3
  babel-plugin-jsx-control-statements: ^3.2.8
